### ISSUE TITLE
maxdist not passed through

### ISSUE THREAD

**Issue by suragnair** [caleblareau/errorcorrect_10xatac_barcodes#1]
https://github.com/caleblareau/errorcorrect_10xatac_barcodes/blob/5b9380b92a156c600b10d1dfa018b49604fbde41/process_10x_barcodes.py#L115

`wl_idxs` is unused and then when `gen_nearby_seqs` is called

https://github.com/caleblareau/errorcorrect_10xatac_barcodes/blob/5b9380b92a156c600b10d1dfa018b49604fbde41/process_10x_barcodes.py#L140

`maxdist` doesn't go through

**Comment by caleblareau** [comment]
thanks for catching this-- just updated.
